
sum_res = zeros(5,5);
sum_fig = zeros(5,128,128);
max_res = zeros(5,5);
max_fig = zeros(5,128,128);
vec_res = zeros(5,5);
vec_fig = zeros(5,128,128);
cos_res = zeros(5,5);
cos_fig = zeros(5,128,128);
gray_res = zeros(5,5);
gray_fig = zeros(5,128,128);

for im = 1:5
    
    disp(strcat('Working on im: ', num2str(im)))
    
    input_file = strcat('..\dataset\testset\', num2str(im), '.jpg');
    edge_file = strcat('..\dataset\testset\', num2str(im), '_edge.png');
    
    image = double(imread(input_file)) ./ 255;
    edge = imread(edge_file);
    
    %Sum
%     pheromone_map = ACORGBsum(image, ...
%         'BaselineHeuristic', ...
%         'AntCreation', ...
%         'RandomAntInitialization', ...
%         'EightNPosSteps', ...
%         best_parameters(2,1), ...
%         best_parameters(2,2), ...
%         best_parameters(2,3), ...
%         best_parameters(2,4), ...
%         best_parameters(2,5), ...
%         best_parameters(2,6), ...
%         best_parameters(2,7));
%     
%     [fig, eval] = Eval_Pheromones(edge, pheromone_map);
%     sum_res(im,:) = eval;
%     sum_fig(im,:,:) = fig;
%     
%     % Max
%     pheromone_map = ACORGBmax(image, ...
%         'BaselineHeuristic', ...
%         'AntCreation', ...
%         'RandomAntInitialization', ...
%         'EightNPosSteps', ...
%         best_parameters(1,1), ...
%         best_parameters(1,2), ...
%         best_parameters(1,3), ...
%         best_parameters(1,4), ...
%         best_parameters(1,5), ...
%         best_parameters(1,6), ...
%         best_parameters(1,7));
%     
%     [fig, eval] = Eval_Pheromones(edge, pheromone_map);
%     max_res(im,:) = eval;
%     max_fig(im,:,:) = fig;
%     
%     %Vec
%     pheromone_map = ACOEdgeDetection(image, ...
%         'VectorHeuristic', ...
%         'AntCreation', ...
%         'RandomAntInitialization', ...
%         'EightNPosSteps', ...
%         best_parameters(5,1), ...
%         best_parameters(5,2), ...
%         best_parameters(5,3), ...
%         best_parameters(5,4), ...
%         best_parameters(5,5), ...
%         best_parameters(5,6), ...
%         best_parameters(5,7));
%     
%     [fig, eval] = Eval_Pheromones(edge, pheromone_map);
%     vec_res(im,:) = eval;
%     vec_fig(im,:,:) = fig;
    
    %Cos
    pheromone_map = ACOEdgeDetection(image, ...
        'CosineHeuristic', ...
        'AntCreation', ...
        'RandomAntInitialization', ...
        'EightNPosSteps', ...
        best_parameters(3,1), ...
        best_parameters(3,2), ...
        best_parameters(3,3), ...
        best_parameters(3,4), ...
        best_parameters(3,5), ...
        best_parameters(3,6), ...
        best_parameters(3,7));
    
    [fig, eval] = Eval_Pheromones(edge, pheromone_map);
    cos_res(im,:) = eval;
    cos_fig(im,:,:) = fig;
    
%     %Gray
%     %Turn RGB image into grayscale image
%     gray = rgb2gray(image);
%     gray = gray(:,:,1);
%     
%     pheromone_map = ACOEdgeDetection(gray, ...
%         'BaselineHeuristic', ...
%         'AntCreation', ...
%         'RandomAntInitialization', ...
%         'EightNPosSteps', ...
%         best_parameters(4,1), ...
%         best_parameters(4,2), ...
%         best_parameters(4,3), ...
%         best_parameters(4,4), ...
%         best_parameters(4,5), ...
%         best_parameters(4,6), ...
%         best_parameters(4,7));
%     
%     [fig, eval] = Eval_Pheromones(edge, pheromone_map);
%     gray_res(im,:) = eval;
%     gray_fig(im,:,:) = fig;
end

