pheromone_map = ACOEdgeDetection('kat.jpg', ...
'VectorHeuristic', ...
'AntCreation', ...
'RandomAntInitialization', ...
'FourNPosSteps', ...
4, 300, 40, 10, 0.1, 0.1, 0.05);

T = func_seperate_two_class(pheromone_map);
imwrite(uint8(abs((pheromone_map >= T) .* 255 - 255)), gray(256), ['test_edge.bmp'], 'bmp');    