% This is an example of how to run Color ACO
% All details are explained in ACOEdgedetection.m
% You can also look at gridsearch.m for more examples
% ACOEdgeDetection.m can be chnaged by giving it other heuristic names.
% VectorHeuristic, CosineHeuristic. (make sure to remove the part where
% the image is turned in to grayscale)

%% Create pheromone maps (multiple in case of ACORGB)
image = double(imread('1.jpg')) ./ 255;
[pheromone_maps, colorhistory] = ACORGB(image, ...
        'BaselineHeuristic', ...
        'AntCreation', ...
        'RandomAntInitialization', ...
        'EightNPosSteps', ...
        6, ...
        40, ...
        20, ...
        1.1, ...
        0.1, ...
        0.05, ...
        0.025);

%% Combine maps for sum method
figure
imshow(mat2gray(squeeze(pheromone_maps(1,:,:) + pheromone_maps(2,:,:) + pheromone_maps(3,:,:))))

%% Create pheromone maps gray

%Turn RGB image into grayscale image
gray = rgb2gray(image);
gray = gray(:,:,1);

[pheromone_map, grayhistory] = ACOEdgeDetection(gray, ...
        'BaselineHeuristic', ...
        'AntCreation', ...
        'RandomAntInitialization', ...
        'EightNPosSteps', ...
        8, ...
        40, ...
        20, ...
        1.1, ...
        0.1, ...
        0.05, ...
        0.025);

%%
figure
imshow(mat2gray(pheromone_map(:,:)))

